#!/usr/bin/env node
const target=process.argv[3] || './bin/lean.css'

const
fs=require('fs'),
CleanCSS = require('clean-css'),
src= `@import ${process.argv[2] || "src/css/index.css"};`

new CleanCSS({rebase:false,sourceMap:true,target:target}).minify(src, (err, minified)=>{
    if (err) return console.error(err)
    fs.writeFile(target, minified.styles, 'utf8', (err)=>{
        if (err) return console.error(err)
        fs.writeFile(target+'.map', minified.sourceMap.toString(), 'utf8', (err)=>{
            if (err) return console.error(err)
            console.log('done')
        })
    })
})
